var a = $("#one").html();
console.log(a);
$("#one").html("<p>Hello</p>");
var text = $("#two").text();
console.log(text);
$("#two").text("This is a paragraph");
$("#two").css("background-color","yellow");
var css = $("#two").css("background-color");
console.log(css);
$("#two").prepend("Hello prepend");
console.log($("#two").html());
$("#two").append("Hello append");
$("#two").after("<h1>new heading after paragraph</h1>");
$("#two").before("<h1>new heading before paragraph</h1>");
$('#one').empty();
$("#one").remove();
$("#two").attr("id","abc");
$("#abc").removeAttr("id");
$("h1:nth-child(2)").attr("id", "two");
$("ul").children().css({"color": "red", "border": "2px solid red"});
$( "li.item-a" ).parent().css( "border", "red" );
$( "li.item-a" ).parents().css( "border", "red" );
$( "li.item-a" ).parentsUntil("div").css( "background-color", "yellow" );
$( "li.item-a" ).siblings().css( "background-color", "red" );
$( "li.item-a" ).next().css( "background-color", "pink" );
$( "li.item-a" ).prev().css( "background-color", "pink" );
$( "li.item-a" ).prevAll().css( "background-color", "pink" );
$( "li.item-a" ).nextAll().css( "background-color", "pink" );
$( "li.item-a" ).prevUntil("ul").css( "background-color", "pink" );
$( "li.item-a" ).nextUntil("item-b").css( "background-color", "red" );

